twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        gbrands: '@App\Globals\Brands'
        ggroups: '@App\Globals\Groups'


when@test:
    twig:
        strict_variables: true
